version: "3.3"

services:
  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "${PROJECT_PORT}:80"

  php:
    container_name: php
    build: images/php/${PHP_VERSION}
    volumes:
      - ./projects/${PROJECT_NAME}:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    ports:
      - "9000:9000"